# Generated by Django 4.2.3 on 2023-08-03 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Regist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=15)),
                ('apellido', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=20)),
                ('password2', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=60)),
            ],
        ),
    ]
