# Generated by Django 4.2.3 on 2023-08-03 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regist',
            name='email',
            field=models.EmailField(max_length=150),
        ),
    ]
