# Generated by Django 4.2.3 on 2023-08-03 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesapp', '0002_alter_regist_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regist',
            name='password',
            field=models.CharField(max_length=200),
        ),
    ]
