# Generated by Django 4.2.3 on 2023-08-04 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesapp', '0003_alter_regist_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regist',
            name='email',
            field=models.EmailField(max_length=150, unique=True),
        ),
    ]
