# Generated by Django 4.2.3 on 2023-08-08 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesapp', '0004_alter_regist_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='tarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, null=True)),
                ('titulo', models.CharField(max_length=60)),
                ('nota', models.CharField(max_length=350)),
                ('ceccion', models.CharField(max_length=40)),
                ('link', models.CharField(max_length=400)),
            ],
        ),
    ]
